In [1]:
import numpy as np


In [2]:
my_array = np.array([1,2,3,4,5])

print(my_array)


[1 2 3 4 5]


In [6]:
print(my_array.shape)

(5,)


In [7]:
my_array2 = np.array([[1,2,3],[4,5,6]])
print(my_array2)
print(my_array2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
my_2d_array = np.zeros((2,3))
print(my_2d_array)

[[0. 0. 0.]
 [0. 0. 0.]]
