# 聚合操作

In [2]:
import numpy as np

L = np.random.random(100) # 生成100个0~1之间的随机数数组

In [3]:
L

array([0.75186113, 0.61508027, 0.09708365, 0.70306917, 0.42820705,
       0.78900065, 0.01375272, 0.61303812, 0.39303426, 0.58804524,
       0.69775817, 0.50975937, 0.24961558, 0.27728244, 0.84929384,
       0.70626687, 0.81482314, 0.31645739, 0.05126128, 0.27194687,
       0.32359931, 0.93992986, 0.31482613, 0.70329384, 0.30591046,
       0.10981446, 0.2420331 , 0.41984886, 0.56926011, 0.80761239,
       0.73321151, 0.45541038, 0.86033407, 0.131766  , 0.79914307,
       0.09186284, 0.50278205, 0.07208581, 0.2200567 , 0.0646432 ,
       0.65702454, 0.69026552, 0.08386921, 0.0011112 , 0.08797612,
       0.59044396, 0.33263508, 0.86909006, 0.04108843, 0.79574266,
       0.27459269, 0.21717412, 0.3238919 , 0.31273596, 0.2744333 ,
       0.16861503, 0.38420848, 0.81337769, 0.37050707, 0.84588241,
       0.08370746, 0.56896607, 0.93199402, 0.14553388, 0.47374887,
       0.25408042, 0.9265564 , 0.64880677, 0.12653612, 0.36077619,
       0.28442999, 0.69638317, 0.48092591, 0.74314615, 0.48441

In [4]:
sum(L)

43.69189476782417

In [5]:
np.sum(L)

43.69189476782418

In [6]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array) # np.sum效率是sum()的100多倍

7.97 ms ± 72 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
44.7 µs ± 512 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
np.min(L)

0.0011111996365901211

In [8]:
np.max(L)

0.9399298567747333

In [9]:
big_array.min()

6.513261574969675e-06

In [10]:
big_array.max()

0.9999921875732065

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0) # 在列上聚合， axis = 0 表示沿着行这个维度进行运算， 还可以理解为将第0（行）这个轴压缩掉

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1) # 在行上聚合， axis = 1 表示沿着列这个维度进行运算， 还可以理解为将第1（列）这个轴压缩掉

array([ 6, 22, 38, 54])

In [15]:
np.prod(X) # 返回这个矩阵中所有项目的乘积

0

In [16]:
np.prod(X + 1)  # 对每个元素加1，在把它们乘起来

2004189184

In [17]:
np.mean(X) # 求平均值

7.5

In [18]:
np.median(X) # 求中位数

7.5

In [19]:
np.percentile(big_array, q = 50) # 表示big_array中50%的数都是小于0.500847456386499的

0.500847456386499

In [20]:
np.median(big_array)

0.500847456386499

In [21]:
for percent in [0, 25, 50, 100]:
    print(np.percentile(big_array, q = percent))

6.513261574969675e-06
0.24989775311935622
0.500847456386499
0.9999921875732065


In [22]:
np.var(big_array) # 求big_array的方差

0.08322526530520633

In [23]:
np.std(big_array) # 求big_array的标准差

0.2884878945557444

In [24]:
# 均值为0， 标准差为1， size为1000000
x = np.random.normal(0, 1, size = 1000000)

In [28]:
np.mean(x)

5.985332992565588e-07

In [29]:
np.std(x)

0.9999226749994612

## 索引

In [30]:
np.min(x)

-4.73241352715943

In [31]:
np.argmin(x) # 返回最小值的索引值

709149

In [32]:
x[709149]

-4.73241352715943

In [33]:
np.argmax(x)

28885

In [34]:
x[28885]

4.568395520593914

### 排序和使用索引

In [45]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
np.random.shuffle(x) # 乱序处理
x

array([13,  4,  5, 15,  8,  3,  2, 14, 11,  6,  0,  9,  1,  7, 12, 10])

In [38]:
np.sort(x) # 得到一个排序了的数组，原数组不变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
x

array([13,  4,  5, 15,  8,  3,  2, 14, 11,  6,  0,  9,  1,  7, 12, 10])

In [41]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
X = np.random.randint(10, size = (4, 4)) # 10以内的4,4,随机矩阵
X

array([[5, 9, 5, 6],
       [4, 6, 1, 6],
       [1, 7, 1, 8],
       [9, 0, 3, 4]])

In [46]:
np.sort(X) # 其实就是将每一行都排序 axis默认是1 按照列的方向进行排序

array([[5, 5, 6, 9],
       [1, 4, 6, 6],
       [1, 1, 7, 8],
       [0, 3, 4, 9]])

In [47]:
np.sort(X, axis = 0) # 按照行的方向进行排序，就是列上进行排序

array([[1, 0, 1, 4],
       [4, 6, 1, 6],
       [5, 7, 3, 6],
       [9, 9, 5, 8]])

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
np.random.shuffle(x)
x

array([ 2,  5,  9,  1, 15, 14,  6,  3, 10,  0, 13,  7, 12,  4, 11,  8])

In [51]:
np.argsort(x) # 排序索引， 如：9就是0的索引值

array([ 9,  3,  0,  7, 13,  1,  6, 11, 15,  2,  8, 14, 12, 10,  5,  4],
      dtype=int64)

In [52]:
np.partition(x, 3) # 快排中的partition, 这里指定3，左边都比3小，右边都比3大，但都不是有序的

array([ 1,  2,  0,  3, 15, 14,  6,  5, 10,  9, 13,  7, 12,  4, 11,  8])

In [55]:
np.argpartition(x, 3)

array([ 3,  0,  9,  7,  4,  5,  6,  1,  8,  2, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [56]:
X

array([[5, 9, 5, 6],
       [4, 6, 1, 6],
       [1, 7, 1, 8],
       [9, 0, 3, 4]])

In [54]:
np.argsort(X, axis = 1)

array([[0, 2, 3, 1],
       [2, 0, 1, 3],
       [0, 2, 1, 3],
       [1, 2, 3, 0]], dtype=int64)

In [57]:
np.argsort(X, axis = 0)

array([[2, 3, 1, 3],
       [1, 1, 2, 0],
       [0, 2, 3, 1],
       [3, 0, 0, 2]], dtype=int64)

In [58]:
np.argpartition(X, 2, axis = 1)

array([[0, 2, 3, 1],
       [2, 0, 1, 3],
       [0, 2, 1, 3],
       [1, 2, 3, 0]], dtype=int64)