In [1]:
import numpy as np

In [8]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X = np.arange(15).reshape(3, 5) # 将一个数组修改为矩阵
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [9]:
x.ndim  # 查看数组的维数

1

In [10]:
X.ndim 

2

In [12]:
y = np.arange(27).reshape(3,3,3)
y

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
y.ndim

3

In [14]:
x.shape

(10,)

In [15]:
X.shape

(3, 5)

In [16]:
y.shape

(3, 3, 3)

In [17]:
x.size

10

In [18]:
X.size

15

In [19]:
y.size

27

## numpy.array数据访问

In [20]:
x[:3]

array([0, 1, 2])

In [21]:
x[3:7]

array([3, 4, 5, 6])

In [22]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
# numpy访问矩阵中的元素
X[(0,1)] # 替代x[0][1]方法

1

In [24]:
X[0,1] # 推荐使用的方式！

1

In [25]:
x[::2] # 2为切片步长

array([0, 2, 4, 6, 8])

In [26]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
X[:2, :3] # 访问这个二维数组的前2行，前3列

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
X[:2][:3] # 先取X[:2], 再在此基础上取[:3]前3个元素

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
X[:2, ::2] # 取前2个维度，每个

array([[0, 2, 4],
       [5, 7, 9]])

In [31]:
# 翻转矩阵
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [33]:
X[:, ::-1] # 只在列上反转

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])

In [34]:
X[::-1, :] # 只在行上翻转

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [35]:
X[0, :] # 取第0行，全列

array([0, 1, 2, 3, 4])

In [37]:
X[0, :].ndim

1

In [38]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
X[:, 0] # 只取一列

array([ 0,  5, 10])

In [40]:
subX= X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
subX[0,0] = 100 # 修改子矩阵中的元素会影响原矩阵
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [42]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [44]:
X[0, 0] = 0  # 同理修改原矩阵中的元素会影响子矩阵
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [46]:
# 创建一个跟原矩阵不相关的矩阵需要用到copy()方法
subX = X[:2, :3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [47]:
subX[0,1] = 100
subX

array([[  0, 100,   2],
       [  5,   6,   7]])

In [48]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
X[0,1] = 25
X

array([[ 0, 25,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
subX

array([[  0, 100,   2],
       [  5,   6,   7]])

## Reshape

In [51]:
x.shape

(10,)

In [52]:
x.reshape(2,5) # 将x转换成2 x 5的矩阵(生成一个新的矩阵，x不变)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
B = x.reshape(1, 10)

In [55]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
B.ndim # 是一个二维数组了

2

In [57]:
B.shape

(1, 10)

In [58]:
x.reshape(10, -1)# -1表示不管列这个维度，就是说：根据前面行数自动生成多少列

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [59]:
C = x.reshape(10, -1)
C

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [60]:
C.shape # 10行1列的矩阵

(10, 1)

In [61]:
C.ndim

2

In [63]:
D = x.reshape(5, -1) # 就会生成一个5行2列的矩阵
D

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [64]:
E = x.reshape(-1, 10) # 跟上面正好相反，生成的行数由列数决定
E

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
E.shape # 1行10列

(1, 10)

In [69]:
x.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 合并操作

In [70]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [71]:
x

array([1, 2, 3])

In [72]:
y

array([3, 2, 1])

In [73]:
np.concatenate([x, y]) # 合并两个向量

array([1, 2, 3, 3, 2, 1])

In [74]:
z = np.array([666,666,666])

In [75]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [76]:
A = np.array([[1,2,3], 
              [4,5,6]])

In [77]:
np.concatenate([A, A]) # 两个2 x 3合并，变成了4 x 3的矩阵

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
# 要想横向扩展，就是将其变成2 x 6的矩阵
# 可以理解为：原来有两个样本，每个样本有三个特征，现在又来了两个样本，这两个样本有三个不同的特征
np.concatenate([A, A], axis = 1) # axis：轴，默认为0，就是以第一维为轴，现在将轴设置为1， 就是以第二维为轴合并

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
np.concatenate([A, z]) # 只有两个维度相同的矩阵才能合并

ValueError: all the input arrays must have same number of dimensions

In [80]:
np.concatenate([A, z.reshape(1, -1)]) # 首先将z变成1 x 3的矩阵

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [81]:
# 替代上面操作的一个简便写法 np.vstack() 在垂直的方向上将数据叠在一起， 两个矩阵列数必须一致
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [82]:
B = np.full((2,2),100) # 创建一个 2 x 2，每个元素都是100的矩阵
B

array([[100, 100],
       [100, 100]])

In [83]:
np.hstack([A, B]) # 在水平方向上将数据叠在一起，两个矩阵行数必须一致

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [84]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [86]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [87]:
np.split(x, [3])

[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [88]:
A = np.arange(16).reshape((4,4))

In [89]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.split(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [91]:
a1, a2 = np.split(A, [2])

In [92]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
np.split(A, [3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [95]:
np.split(A, [2], axis = 1) # 在列上进行分割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [96]:
# numpy的简化方法, 在垂直方向分割
np.vsplit(A, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [97]:
# numpy的简化方法, 在水平方向分割
np.hsplit(A, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [98]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
x, y = np.hsplit(A, [-1]) # -1 表示从后面取第一个为y, 然后剩下来的给x

In [100]:
x

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [101]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [103]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
A[:,0] # : 取所有行，然后0表示取每行的第一列

array([ 0,  4,  8, 12])